version: '3.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: pgpassword
      DB_HOST: postgres
      REST_HOST: "http://host.docker.internal:3000"
      REST_HOST_CLIENT: "http://localhost:3000"
      REST_API_KEY: WhBO1EMyrWREyjIySrSFA2LQU2C0jVHU
      SOAP_HOST: "http://host.docker.internal:3001"
      SOAP_API_KEY: F9ikNrL1qNbi1m18YNhBSwFNc502W5AYBSeUyxgzTbpaxxxiiq6D1ZJKmaEB
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgpassword}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres: